# Generated by Django 5.1.4 on 2025-01-03 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_leaderboard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaderboard',
            name='user',
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='user_name',
            field=models.CharField(default='Anonymous', max_length=255),
        ),
    ]
